### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by LucaUssi** [multipath-rtp/gst-mprtp#1]
HI,
I’m Luca , computer science student, in Pisa University.
I‘m using the “gst-mprtp” code for a project.
I have used the last version loaded. I have used it with "--profile=215" but after a few seconds I have obtained a Segmentation Fault. I send you the gdb backtrace in "[mylog2.txt](https://github.com/multipath-rtp/gst-mprtp/files/171614/mylog2.txt)".
Could you please tell me what is the problem?
Looking forward some news from you,
best regards
                     Luca Ussi

**Comment by balazskreith** [comment]
Hi Luca,
The profile num indicated that you are using auto_rate_and_cc control, which is under test now in a single flow case. I will examine whats going on in multiple flow case. Now try it by using --profile=151 (215-64) and see if the problem remains. I will inform and commit this issue soon, when we are here with the cc tests.

Also git pull now, and see the readme file at https://github.com/multipath-rtp/gst-mprtp, because I changed the testbed setup scripts. It got a bit refactored, hopefully a little bit easier to use.

**Comment by LucaUssi** [comment]
Hi Balázs,
I did  the test using --profile=151 and it doesn’t occur the Segmentation Fault, but the incoming video  goes in spurts and I can not see it clearly.
Best regards.

**Comment by LucaUssi** [comment]
I observed that with the old "setup_test_enviroment"+"sudo ip netns exec [ns0/ns1] bash"+ "setup_[ns0/ns1].sh" the received video is ok.
I hope that this can be useful for you.

**Comment by balazskreith** [comment]
It was. Can you change the latencies in the new environment? 
Latencies are applied on virtual interfaces by running setup_ns_snd.sh, and setup_ns_rcv.sh scripts.
subflow1,2,3 has 50,150,300ms one way delay, means 100,200,600 round trip.
Try change the latencies on subflows by altering the scripts (for an instance 100,100,100 first and then spread out) and see whats going on.

**Comment by LucaUssi** [comment]
Hi,
I've changed the latencies in the new environment and now it works.
Thank you for your help.
Best regards.

**Comment by balazskreith** [comment]
I reopened this issue for being it visible for later commit addressing the segment fault in the case of auto_rate_and_cc is used.
