### ISSUE TITLE
Test 

### ISSUE THREAD

**Issue by LucaUssi** [multipath-rtp/gst-mprtp#3]
Hi,
Is there a test that allow to test the protocol's behavior when one or more subflows have a loss of packets?
Best regards.

**Comment by balazskreith** [comment]
Hi Luca,

In short: I think thats not an MPRTP protocol issue.

The protocol itself [1] describes how to extend RTP header and how to embed RTCP report in order to be used on multiple path at the same time. The responsibility for reacting losts and handling congestions are lying in the application if it implements that kind of service (Also this is not entirely true, since we can transmit RTP on the top of TCP, which has its own congestion controlling mechanisms and it reacts to losses automatically). 
Inside of the application we also need to decouple the responsibility of processing reports, checking streams integrity, react losses, requesting part of original byte streams, etc.... 

To be short: I think rtpbin can be setup to react losses and requesting packets again, but for that I think you need a not living streams, but thats only my guess. Check out the rtpbin object properties at [2].(do-retransmission property seems a good start)
Also you can change the distribution rate amongst the subflow manually right now. There is a method inside of ./server called _random_rate_controller, and this gives new random weights to subflows. If you have an event or signal indicate that a loss happened, you can react to itby redistributing the rates between the flows.
We are working on a new kind of service inside of the application automatically react losses and redistribute the sending rates amongst the subflows, for handling congestions, but thats not ready yet, and will not retransmit packets if they losts. Packet retransmission must be requested by other elements.

I hope It was useful.

[1] https://tools.ietf.org/html/draft-singh-avtcore-mprtp-10
[2] https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good-plugins/html/gst-plugins-good-plugins-rtpbin.html

**Comment by LucaUssi** [comment]
Hi Balázs,
thank you very much for the help. Can you tell me if the lost packets are reported in the log files? I've noticed that the "lost_bytes" of the "sndctler.log" is always 0.
Best regards.

**Comment by balazskreith** [comment]
That's because at the code I found the following: :)
report->lost_bytes      = 0;//Fixme
So right now it always 0.

You can use the the snd_reports.log, where the fraction_lost is printed out after a report, but report only sent if auto_rate_and_cc turned on, otherwise mprtp don't send report about path, because why?!. (Okay it might be rewised)

You can setup min_rate and _max_rate to the target_bitrate and turn the auto_rate_and_cc. By setup the max_rate and min_rate you can prevent the rate to fluctuating and you will get the logs for reports.

Although its a little bit "hacking", so consider it as a temporary solution.
